import SiteShell from "@/components/SiteShell";
import ContactMap from "@/components/ContactMap";
import { Clock3, MapPin, Navigation, PhoneCall, Route } from "lucide-react";

const directionsUrl = "https://www.google.com/maps/dir/?api=1&destination=14.3517,100.5774&travelmode=driving";

function GoogleMapsIcon() { return <svg className="google-maps-icon" viewBox="0 0 24 24" width="22" height="22" aria-hidden="true" focusable="false"><path fill="#34A853" d="M12 2.1A7.9 7.9 0 0 0 4.1 10c0 5.3 7.9 11.9 7.9 11.9S19.9 15.3 19.9 10A7.9 7.9 0 0 0 12 2.1Z" /><path fill="#4285F4" d="M12 2.1A7.9 7.9 0 0 0 4.1 10c0 5.3 7.9 11.9 7.9 11.9V10Z" /><path fill="#FBBC04" d="M12 21.9S19.9 15.3 19.9 10A7.9 7.9 0 0 0 12 2.1v8.2Z" /><circle cx="12" cy="10.1" r="3.2" fill="#EA4335" /><circle cx="12" cy="10.1" r="1.35" fill="#fff" /></svg>; }

export default function Contact() { return <SiteShell><div className="contact-page">
  <section className="hero-section contact-hero contact-hero--background contact-hero--filled"><img className="hero-image" src="/hero-neon-tire-2560.webp" srcSet="/hero-neon-tire-1280.webp 1280w, /hero-neon-tire-2560.webp 2560w" sizes="100vw" alt="ภาพยางรถยนต์ในอู่ไฟนีออน" /><div className="hero-wash" /><div className="container hero-content contact-hero-content"><p className="hero-kicker"><span className="pulse-dot" /> ติดต่อร้าน / ศูนย์บริการ</p><h1 className="thai-headline">ติดต่อเรา<em>ร้านบริการ</em></h1><p className="contact-hero-description">ติดต่อ ร้าน เป้าการยาง ร้านยางรถยนต์ อยุธยา ใน ต.ธนู อ.อุทัย เพื่อนัดหมายใส่ยาง ปะยาง หรือปรึกษาเรื่องดูแลล้อ</p></div></section>
  <section className="section-pad pt-0"><div className="container contact-grid"><ContactMap /><div className="contact-data"><p className="eyebrow text-cyan-300">ช่องทางการติดต่อ</p><h2 className="thai-headline">พร้อมเสมอ<br />ทุกการเดินทาง</h2><div className="contact-line"><PhoneCall size={20} /><div><span>เบอร์โทรศัพท์</span><strong>035-213134</strong><small>โทรสอบถามบริการยางและนัดหมาย</small></div></div><div className="contact-line"><Clock3 size={20} /><div><span>เวลาเปิดทำการ</span><strong>จันทร์ — อาทิตย์ / 08:00 — 17:00</strong><small>บริการร้านจบเวลา 16:45 น.</small></div></div><div className="contact-line"><MapPin size={20} /><div><span>ที่ตั้งและแผนที่</span><strong>9J36+4VX ตำบลธนู อำเภออุทัย จ.พระนครศรีอยุธยา 13210</strong><small>เปิดแผนที่ดูพื้นที่บริการและเส้นทางเดินทาง</small></div></div></div></div></section>
  <section className="local-search-section" aria-labelledby="local-search-title"><div className="container local-search-grid"><div><p className="eyebrow text-cyan-300">ร้านยางในอำเภออุทัย / อยุธยา</p><h2 id="local-search-title" className="thai-headline local-search-heading">กำลังมองหา<br /><em>ร้านยาง อยุธยา ?</em></h2></div><div className="local-search-copy"><p className="local-search-copy__lead">ร้าน เป้าการยาง คือ ร้านยางใน ต.ธนู อ.อุทัย จ.พระนครศรีอยุธยา ให้บริการยางรถเก๋ง รถกระบะ รถ 6 ล้อ และรถ 10 ล้อ พร้อมปะยาง ถ่วงล้อ และบริการนอกสถานที่ตามการนัดหมาย</p><p className="local-search-copy__lead">ก่อนโทรสอบถาม สามารถแจ้งประเภทรถ ขนาดยางที่ใช้อยู่ หรืออาการเบื้องต้นที่พบ เพื่อให้ร้านช่วยแนะนำการสอบถามและเตรียมบริการได้ตรงความต้องการ</p><aside className="local-route-guide" aria-label="คำแนะนำเส้นทางจากจุดสังเกตในอยุธยา"><Route size={22} aria-hidden="true" /><div><span className="local-route-guide__eyebrow">แนะนำเส้นทางจากจุดสังเกต</span><p>ใช้จุดสังเกตต่อไปนี้เพื่อเข้าพื้นที่ตำบลธนู แล้วเปิด Google Maps ไปยังพิกัดร้านเพื่อดูเส้นทางที่เหมาะกับสภาพจราจรขณะเดินทาง</p><ul className="local-route-guide__list"><li><strong>จากถนนสายเอเชีย / ทางหลวงหมายเลข 32</strong> — เลือกจุดหมาย “เป้าการยาง” ใน Google Maps เมื่อเข้าใกล้พื้นที่อำเภออุทัย</li><li><strong>จากตลาดแกรนด์</strong> — ใช้ตลาดในตำบลธนูเป็นจุดสังเกตใกล้ร้าน แล้วกดนำทางต่อไปยังพิกัดร้านโดยตรง</li></ul><span className="local-route-guide__note">เส้นทางจริงอาจเปลี่ยนตามสภาพจราจรและทางเข้าในขณะนั้น</span></div></aside><p className="local-search-copy__location">ร้านตั้งอยู่ที่ <strong>9J36+4VX ตำบลธนู อำเภออุทัย จังหวัดพระนครศรีอยุธยา 13210</strong><br />เปิดทุกวัน 08:00–17:00 น. หากต้องการสอบถามบริการหรือเข้ารับบริการ สามารถโทร <a href="tel:035213134">035-213134</a> หรือเปิดแผนที่เพื่อวางเส้นทางได้ทันที</p><div className="local-search-actions"><a className="local-search-action" href={directionsUrl} target="_blank" rel="noreferrer"><GoogleMapsIcon /> ดูเส้นทางมาที่เป้าการยาง</a></div></div></div></section>
  <a className="mobile-map-bar" href={directionsUrl} target="_blank" rel="noreferrer" aria-label="นำทางไปยังเป้าการยางด้วย Google Maps"><Navigation size={18} aria-hidden="true" /><span>นำทางไปร้าน</span><small>Google Maps</small></a>
</div></SiteShell>; }
